length = float(input('Enter the length '))
breadth = float(input('Enter the breadth '))
height = float(input('Enter the height '))
area = 2*(length*height + length*breadth + breadth*height)
print('Area of Surface cuboid: ',area)
